image: python:3.11

stages:
  - docs


pages:
  stage: docs
  tags:
    - python
  script:
    - pip install -r ./doc/user/requirements.txt
    - python ./scripts/doc/userDocGenRST.py
    - sphinx-build -M html ./doc/user/ ./doc/user/_build
    - mv ./doc/user/_build/html/ ./public/
  artifacts:
    paths:
      - public