#include "TEST_CairnCore.h"
#include <iostream>
#include "StudyCTest.h"


using namespace std;

/* This test reads study formation_cairn.json, then save it as formation_cairn_saved.json.

   After, it reads formation_cairn_saved.json and formation_cairn_dataseries.csv,
   then executes a simulation for the study formation_cairn_saved.json.

   At the end, it compares the result formation_cairn_saved_Results.csv to the reference 
   formation_cairn_Results_Reference.csv which is generated from formation_cairn.json using the GUI.
*/

int main()
{
	CairnAPI m_Cairn;
	StudyCTest vTest("", "");
	std::string vSolverType = vTest.TrySolver(m_Cairn, "Cplex");
	if (vSolverType == "Highs") return noError; // No test if solver is Highs

	CairnAPI::OptimProblemAPI m_Problem;

	//File Paths
	const std::string StudyRoot = TEST_RESULTS + (std::string)"/saveStudy/";
	const std::string vFileName = StudyRoot + (std::string)"/formation_cairn.json";
	const std::string vFileNameSaved = StudyRoot + (std::string)"saved/formation_cairn_saved.json";
	const std::string TimeseriesFileName = StudyRoot + (std::string)"/formation_cairn_dataseries.csv";
	const std::string ResultFileName = StudyRoot + "saved/formation_cairn_saved_results_Results.csv";

	if (fs::exists(StudyRoot)) {
		fs::remove_all(StudyRoot);
	}
	if (!fs::exists(TEST_RESULTS)) {
		fs::create_directory(TEST_RESULTS);
	}
	fs::create_directory(StudyRoot);
	fs::copy_file(TEST_DATA + (std::string)"/formation_cairn.json", vFileName);
	fs::copy_file(TEST_DATA + (std::string)"/formation_cairn_dataseries.csv", TimeseriesFileName);

	//string const ReferenceStudyFileName = TEST_DATA + (std::string)"/formation_cairn.json";
	string const ReferenceResultFileName = TEST_DATA + (std::string)"/formation_cairn_Results_Reference.csv";

	TESTAPI("read study file from the data: " + vFileName,
		m_Problem = m_Cairn.read_Study(vFileName)
	)

	//Test setting port attribute
	std::shared_ptr<CairnAPI::MilpComponentAPI> ely_pem = m_Problem.get_Component("ELY_PEM");
	std::shared_ptr < CairnAPI::MilpPortAPI> ely_pem_PortL0 = ely_pem->get_Port("PortL0");

	ely_pem_PortL0->set_SettingValue("Coeff", 2.0);

	TESTAPIBOOL("Verify the value of ELY_PEM.PortL0.coeff",
		TestUtils::compare_scalar(ely_pem_PortL0->get_SettingValue("Coeff"), 2.0, eDouble)
	)

	//Re-set the coeff value to 1.0
	ely_pem_PortL0->set_SettingValue("Coeff", 1.0);

	t_list ReferenceListOfComponent = m_Problem.get_Components();

	//Save study using a relative path
	TESTAPI("write study file in the file path: " + vFileNameSaved,
		m_Problem.save_Study("saved/formation_cairn_saved.json") 
	)

	//CompareJsonFiles doesn't accept missing parameters
	//TESTAPI("Compare json",
	//	TestUtilsJson::CompareJsonFiles(vFileName, ReferenceStudyFileName)
	//)

	CairnAPI m_Cairn2;
	CairnAPI::OptimProblemAPI m_Problem2;

	TESTAPI("read study file generated by m_Problem.save_Study: " + vFileNameSaved,
		m_Problem2 = m_Cairn2.read_Study(vFileNameSaved)
	)

	TESTAPI("Read the Timeseries from the file path : " + TimeseriesFileName,
		m_Problem2.add_TimeSeries(TimeseriesFileName)
	)

	CairnAPI::SolutionAPI vSolution;

	TESTAPI("Run",
		vSolution = m_Problem2.run()
	)
	vSolution.exportTimeSeries();

	std::shared_ptr<CairnAPI::MilpComponentAPI> ely_pem_2 = m_Problem2.get_Component("ELY_PEM");

	ely_pem_2->get_IndicatorNames();
	ely_pem_2->get_IndicatorValues("PLAN");

	TESTAPIBOOL("Compare results", 
		TestUtils::ComparaisonCsvFile(ResultFileName, ReferenceResultFileName)
	)
	
	return noError;
}