name: cairn Workflow
on:
  push:
    branches:
      - ci-cd #TBR

jobs:
  cairn-build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Update submodules
        run: git submodule update --init --recursive --remote
      
      - name: buildALL
        run: ./buildAll.bat debug open
      - name: TNR Tests
        run: ./GenericAppEnv.bat release && ./tests/scripts/startPytest.bat release Cairn 0 ./tests/reports/Cairn-TNR.xml tests

      #TODO TNR 
