name: documentations

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install -r ./doc/user/requirements.txt
          python ./scripts/doc/userDocGenRST.py
      - name: Sphinx build
        run: |
          sphinx-build -M html ./doc/user/ ./doc/user/_build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/user/_build/html
          force_orphan: true
