name: documentations

# on:
#   push:  #disabling auto run
#     branches:
#       - main
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    runs-on: windows-latest

    env:
      GITHUB_URL: https://github.com/CEA-Liten/CairnOpen
      VERSION: 5.4.0
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Define WHL variables and download package
        shell: bash
        run: |
          set -e
          WHL_FILENAME="cairn-${VERSION}-cp313-cp313-win_amd64.whl"
          WHL_URL="${GITHUB_URL}/releases/download/${VERSION}/${WHL_FILENAME}"
          echo "WHL_FILENAME=$WHL_FILENAME" >> $GITHUB_ENV
          echo "WHL_URL=$WHL_URL" >> $GITHUB_ENV
          echo "Downloading wheel from $WHL_URL"
          mkdir -p bin
          curl -L -o "$WHL_FILENAME" "$WHL_URL"
          mv "$WHL_FILENAME" bin/
      - name: build Doc
        run: cmd.exe /c "buildAll.bat" nothing open no-wheel no-deps env buildDoc
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/user/_build/html
          force_orphan: true
